### ISSUE TITLE
Manual 'Load More' items appear

### ISSUE THREAD

**Issue by simondrabble** [jackrabbitsgroup/angular-infinitescroll#4]
I would expect infinite scrolling to be automatic - as the user scrolls, the list container will fill up with more elements from data. This is not what happens. Instead, I get a Load More item at the very top of the list (presumably before any data has been populated into the list), then a number of real data items, then another Load More item - clicking that then populates the list with additional data items. Of course, to go backwards through the list I then have to click the top Load More item.

This is from a near-identical (only the data items are different) copy of the first example.

**Comment by lukemadera** [comment]
Try using the scrollLoad or pageScroll attributes as noted in the documentation:
https://github.com/jackrabbitsgroup/angular-infinitescroll/blob/master/infinitescroll.js
